Update CLA submission instructions.
IntelLabs/ScalableVectorSearch pull request #29
Opened 2024-03-01 00:53 UTC by hildebrandmw

The original submission instructions assumed we had something like [cla-assistant](https://github.com/cla-assistant/cla-assistant) set up to automate CLA on pull requests. Such automation is not yet needed. This PR updates the CLA instructions to indicate that CLAs should be sent to `svs-maintainers@intel.com` and indicates that digital signatures directly in the Markdown files are acceptable.

2024-03-01 01:17 UTC, ibhati approved these changes

2024-03-01 19:07 UTC, aguerreb requested changes
There is a typo in the first sentence, "constributor" instead of "contributor". Otherwise, it looks good to me.

2024-03-01 22:01 UTC, hildebrandmw commented
Fixed! Thanks for catching that! I should really probably enable Vim's spell-checker by default ...

2024-03-01 23:24 UTC, marianotepper approved these changes

2024-03-07 05:38 UTC, aguerreb approved these changes

2024-04-12 17:41 UTC, mihaic commented
Closed in PR #33.

2024-04-12 17:41 UTC, closed without merging